### ISSUE TITLE
Can't make listener work

### ISSUE THREAD

**Issue by kjeffris** [devinaconley/arduino-plotter#15]
I am trying to view just simple changes in resistance in real time for a presentation I am giving tomorrow, and I can't seem to make this work.  I am using Atom PlatformIO with an arduino 101, and am using the following code:

```
#include "Arduino.h"
#include "Plotter.h"

double rVal = 10e3; // Known resistor value.
int iPin = A2;   // Pin our input is connected to.
double vIn = 5;   // Input voltage corrected for loss.
Plotter p; // Global Plotter variable
double out; // Global output variable
double resistance;

void setup()
{
  // put your setup code here, to run once:
  p = Plotter();          // Initialize Plotter
  p.AddTimeGraph( "Resistance", 500, "Resistance", resistance);

void loop()
{
  // put your main code here, to run repeatedly:
  out = analogRead(iPin);            // Our output voltage
  resistance = (out * vIn) / (vIn - out);  // The resistance between leads
  p.Plot();
}

```
However when I open the Listener app it switches off between displaying 
<img width="390" alt="screen shot 2017-03-31 at 5 01 02 pm" src="https://cloud.githubusercontent.com/assets/21269660/24573090/b82257d2-1633-11e7-9d8e-5db0d559654f.png">
and
<img width="373" alt="screen shot 2017-03-31 at 5 01 10 pm" src="https://cloud.githubusercontent.com/assets/21269660/24573092/ba390b6a-1633-11e7-8ac6-cd393a0fd1a1.png">.

I am running Mac OS Sierra
Any advice?

**Comment by devinaconley** [comment]
Are you able to run the examples?

**Comment by devinaconley** [comment]
Closing this. Feel free to reopen if you still have a problem.
