### ISSUE TITLE
Unable to locate Plotter.h when running on RPI

### ISSUE THREAD

**Issue by honupirate** [devinaconley/arduino-plotter#17]
When attempting to run the plotter on a Raspbian RPI 3 the Arduino IDE keeps returning an Error compiling message.  Claiming that it is unable to locate "Plotter.h",  saying that there is no such file or directory and terminating the program.  Any help in resolving this issue would be greatly appreciated.

**Comment by devinaconley** [comment]
Did you install via the library manager or by zip file?

**Comment by honupirate** [comment]
We figured it out!  Thanks for your response.  You can mark it as resolved
on github.


*James Laville*
*STEAM Facilitator *
*Roncalli Catholic High School*
6401 Sorensen Parkway
Omaha, NE 68152

**Comment by devinaconley** [comment]
Glad to hear. No problem
