### ISSUE TITLE
Specified folder/zip file does not contain a valid library

### ISSUE THREAD

**Issue by jimrd** [devinaconley/arduino-plotter#18]
Get this message when trying to add arduino-plotter-master.zip to arduino IDE.

**Comment by devinaconley** [comment]
Are you using the zip of this repository? Should be using the one linked to here https://github.com/devinaconley/arduino-plotter/wiki/Installation-and-Quickstart

**Comment by jimrd** [comment]
Yes, that works. Thank you.

**Comment by devinaconley** [comment]
Great, closing this
