### ISSUE TITLE
 please add option to log files in text file and option to change between com ports[enhancement]

### ISSUE THREAD

**Issue by amrithmmh** [devinaconley/arduino-plotter#22]
first of all this is really a good application/library but adding few more basic features will make it the best

**Comment by devinaconley** [comment]
By logging to a text file, do you mean a save data feature? If so that is being tracked here: https://github.com/devinaconley/arduino-plotter/issues/12

The different serial ports should be supported already. The listener scans each port for streaming data on startup. Is that not working for you?

**Comment by amrithmmh** [comment]
@devinaconley thank you
yes it works fine
i have mutiple questions 
1.Is it possible to add grid to the graphs?
2.can the graph be scaled smaller in the code?
3.display data like the frequency for each data stream

again thank you it even works for 6 channel plots

**Comment by Chritzel** [comment]
I imagine @amrithmmh wants to switch between several different devices at different COM-ports, is that correct?

I also have some more ideas of my own (including the ability to fix the dimensions / scaling of the graphs) and will probably try to implement some of them on my fork over the next few weeks. If you have any interface-design ideas for the debugging-console or data-logging features, @devinaconley, I will also see if I can support you in implementing those.

**Comment by devinaconley** [comment]
If there are multiple devices streaming plotting info on different ports, launching multiple listeners should work. Now... continuing to listen/scan against open ports, attaching to multiple streams in parallel, and consolidating graphs within a single listener would be much more graceful... But I think that is a good deal of work for a niche situation.

Fixed dimensions and scaling of graphs would be a great feature. I consider that a large improvement over the current approach of estimating time-scale with number of points. If you open an issue for that, we can track is and discuss details.

I will tag you in the tickets associated with debugging console and data saving

Thanks for the support @Chritzel !

**Comment by devinaconley** [comment]
Tracking the fixed axis limits here #27 

Closing this ticket

**Comment by amrithmmh** [comment]
thank you @devinaconley
