### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by clplaneguy** [devinaconley/arduino-plotter#28]
In the Arduino IDE, I can use the Serial Plotter to see a live display of the variables values as the program runs.  I also use Veusz graph plotting software to graph the data after the run is over.  Veusz is much better at graphing than the Arduino IDE.  Veusz also has a feature to collect data from a file every 0.1 sec (and other).  I would like to be able to do the same thing in PlatformIO.  Is this possible?  I can use an external Terminal program.  But how do I get a live plot.

platformio lib install 850
Does not work.

Processing 3.5.3 is installed.
Arduino-plotter 2.3.3 is installed. Plotter 2.3.3 is installed.
SerialPlot v0.10.0 is installed

However, when I try to run the arduino-plotter example I get the message

`src\main.cpp:2:21: fatal error: Plotter.h: No such file or directory
`
The following commands do not work.

`platformio lib install 850`

`platformio lib install "Plotter"`

`pio lib install "Plotter"`

This sounds like three paragraphs and three apps.

Processing and Listener

Arduino IDE

SerialPlot

I am not sure this is correct.

**Can you please elaborate?**

**Comment by devinaconley** [comment]
Please follow the instructions for setup here:
https://github.com/devinaconley/arduino-plotter/wiki/Installation-and-Quickstart

**Comment by devinaconley** [comment]
Closing this. Feel free to reopen if there is a more specific problem.
