### ISSUE TITLE
Listener for Atom Text Editor

### ISSUE THREAD

**Issue by agent-r** [devinaconley/arduino-plotter#32]
Hey there,

i did a listener Package for Atom, you find it at:

https://atom.io/packages/serial-plotter
https://github.com/agent-r/Serial-Plotter

maybe you want to add this to your documentation.

**Comment by devinaconley** [comment]
Hey @agent-r - thanks for building this

Added here:
https://github.com/devinaconley/arduino-plotter/wiki/Ecosystem
