### ISSUE TITLE
Broken link in wiki

### ISSUE THREAD

**Issue by mikeperrotta** [devinaconley/arduino-plotter#39]
In the wiki page [Installation and Quickstart](https://github.com/devinaconley/arduino-plotter/wiki/Installation-and-Quickstart), the link in 
>(See page for [Issue with stand-alone listener on Mac OS X](https://github.com/devinaconley/arduino-plotter/wiki/Issue-with-stand-alone-listener-on-Mac-OS-X))

goes nowhere. It should point to https://github.com/devinaconley/arduino-plotter/wiki/Troubleshooting#issue-with-stand-alone-listener-on-mac-os-x. Cheers!

**Comment by devinaconley** [comment]
Fixed, thanks!
