### ISSUE TITLE
Serial port printing symbols

### ISSUE THREAD

**Issue by maguro666** [devinaconley/arduino-plotter#40]
Hi,

 i'm relatively new to arduino so apologies for any newbie mistakes.

i've been trying to use the plotter library with an arduino uno to visualize analog readings from pressure sensors. however, upon trying even the simplest quickstart example code, the serial monitor will first print out some proper values, before starting to rapidly print random symbols: (below is the output from uploading the quickstart code)

`{"t":0,"ng":1,"48833446]}]}#
{"t6434464]}]}#
{"t":129,"g":[{"d":[1.61397123]}]}#
{"t":132,"g":[{"d":[1.65116453]}]}#
{"t":135,"g":[{"d":[1.68833446]}]}#
{"t":138,"g":[{"d":[1⸮S⸮@	'>⸮K⸮$⸮,⸮t⸮"⸮H⸮x⸮⸮K
⸮⸮⸮>⸮⸮q⸮ڲ⸮H⸮⸮⸮H⸮⸮⸮%[
⸮f⸮⸮⸮-$<⸮⸮,⸮⸮}⸮⸮Z⸮а⸮⸮,⸮9⸮⸮⸮!Z$⸮⸮⸮⸮⸮0⸮)0=mƎ-⸮-צ%⸮⸮N⸮p⸮⸮i⸮⸮⸮/⸮=S⸮=⸮⸮⸮T⸮⸮X⸮Q⸮nƑ⸮E⸮⸮o[Z[^⸮ڧ⸮⸮o⸮O⸮
P
-K/KO/[
⸮H⸮sJ⸮=,⸮⸮-V⸮Rq⸮^`M⸮⸮)շ⸮շ⸮5I⸮4H⸮$S⸮⸮⸮%⸮⸮tt⸮X⸮R^
⸮⸮:⸮8J⸮9,⸮⸮-⸮p⸮⸮-W⸮⸮⸮⸮⸮^⸮T[⸮Z⸮⸮⸮⸮⸮Tn⸮T⸮⸮X⸮U,⸮X\[{+⸮=d⸮⸮⸮"⸮⸮`⸮⸮&⸮⸮
⸮<⸮$⸮x⸮,V⸮⸮)⸮-Sjʇ⸮.=⸮⸮}⸮z=⸮⸮⸮⸮/⸮⸮⸮H⸮$ ⸮C⸮⸮X⸮],$⸮⸮⸮⸮x8)⸮=,
JmV*⸮j,q⸮,m,⸮⸮⸮HM<⸮ ⸮⸮І
⸮C5ݦX⸮ڇXX⸮|⸮⸮-⸮=)⸮⸮-⸮⸮I(,⸮%I⸮T=!M[⸮-⸮⸮-⸮⸮-⸮⸮KƍN⸮⸮,u,⸮M⸮O}5S⸮겧⸮]⸮=W⸮o⸮⸮⸮⸮^⸮R[
%⸮:⸮8=-⸮-֧J֏I⸮⸮⸮%⸮K⸮ۚ⸮⸮⸮zy⸮⸮$⸮o⸮O⸮&
P[5⸮⸮⸮q⸮8[¬⸮,Ҭ
⸮(-⸮⸮-th,pB,u⸮,⸮⸮D<I⸮,⸮$⸮O⸮S⸮	'⸮*⸮,mZ,⸮m⸮1}⸮ ⸮⸮Җ
C⸮⸮⸮XR⸮X^⸮||⸮-⸮⸮)8*⸮⸮(
⸮P⸮&=⸮$y⸮⸮=H⸮⸮ڳ⸮ִH⸮$M⸮C%⸮⸮⸮⸮$⸮VZ[+-Iˬ)⸮⸮5⸮-⸮J⸮⸮⸮H⸮⸮⸮⸮⸮6⸮⸮⸮⸮Ц
o⸮[J/KN/⸮
i⸮,⸮⸮⸮
⸮⸮OR⸮o⸮⸮⸮⸮f
$t⸮⸮$$⸮x⸮p8)08)⸮RI⸮-zR⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮o⸮O⸮
T` 

i tried running the listener despite this, but the listener is just stuck at "attempting connect on port: COM4" (COM4 is my arduino uno port.).
I am really stuck as to what i am doing wrong, any advice would be greatly appreciated.

Thanks in advance!

**Comment by phdv61** [comment]
What you see is typical of a wrong baud rate.
If I remember well, Listener works at 115200 bauds.
You need to set the speed of the com port at that rate on both your PC and your arduino.
